name: Code Quality Checks

on:
  push:
    branches: [ main, dev, gig-dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Run Checkstyle
      run: ./gradlew checkstyleMain --no-daemon
      continue-on-error: true

    - name: Check code formatting with Spotless
      run: ./gradlew spotlessCheck --no-daemon
      continue-on-error: true

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: checkstyle-report
        path: build/reports/checkstyle/

    - name: Comment PR with Spotless suggestions
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '**Code formatting issues detected!**\n\nRun `./gradlew spotlessApply` to auto-fix formatting issues.'
          })
